config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  # as task lets us link the files
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    raise
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details, "Details" %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed, "Complete" %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>To Do:</h1>
<%= link_to "Create New", tasks_new_path %>

<% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task.id)%></h2>
  <%= check_box_tag :completed, 0, task.completed, class: 'form-control'%>
  <p><%= link_to "Delete", task_path(task.id), method: :delete, data: {confirm: 'Are you sure?'} %></p>
  <% end %>

app/views/tasks/new.html.erb
<h1> Create Task </h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details, "Details" %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= Task %></h1>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= Complete %></p>
<%= check_box_tag :completed, 0, @task.completed, class: 'form-control'%>
<%= link_to "Back", tasks_path %>
<%= link_to "update check", tasks_path %>
<%= link_to "Edit", edit_task_path(@task.id) %>